### ISSUE TITLE
Compiling for Linux

### ISSUE THREAD

**Issue by rchastain** [jonathanmcdermid/Clovis#3]
Hello!

FYI I could compile _Clovis_ 1.2 for Linux 64.

I replaced `#include <intrin.h>` with `#include <x86intrin.h>`.

I replaced `__popcnt64(bitboard)` with `_popcnt64(bitboard)`.

And in three files I replaced `"UCI.h"` with `"uci.h"`.

After that I could compile with a simple `make`.

Good luck with that new engine which has a beautiful name. ;)

Regards.

Roland

**Comment by jonathanmcdermid** [comment]
Thanks a ton for the help/feedback! I have seen how other engines manage OS differences and will add compatibility in a future release.

**Comment by rchastain** [comment]
You are welcome. ;)
I close the issue.
